### ISSUE TITLE
String Interpolation

### ISSUE THREAD

**Issue by jlag34** [MikeMillar/Expresso-Project#2]
In Employees.js on line 171 you have a really long query that goes off the page. Try to break it up using string interpolation:

```
const sql = `'INSERT INTO Employee (name, position, wage, is_current_employee)
VALUES ($name, $position, $wage, $isCurrentEmployee)'`;
```

Using string interpolation you can have multi line strings without using to use a plus sign.

**Comment by MikeMillar** [comment]
I'll keep that in mind in the future when working on this.
