### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [MikeMillar/Expresso-Project#4]
Really nice job on your project. You passed all of the tests and and your project works! Great work building all of your SQL queries and handling the routing. Just keep in mind string interpolation. It can help you when you have variables in a string and also to format long strings. All in all, great job and congrats on finishing your final Capstone Project!

**Comment by MikeMillar** [comment]
Thank you for your review, I'll keep the interpolation in mind when working with it further.
